In [59]:

import tensorflow as tf

a=tf.constant(3.0,dtype=tf.float32)
b=tf.constant(4.0)

total=a+b
print(a)
print(b)
print(total)

write=tf.summary.FileWriter('base')
write.add_graph(tf.get_default_graph())

#writer=tf.summary.FileWriter('./logs',sess.graph)  



Tensor("Const_20:0", shape=(), dtype=float32)
Tensor("Const_21:0", shape=(), dtype=float32)
Tensor("add_19:0", shape=(), dtype=float32)


In [3]:
sess=tf.Session()
print(sess.run(total))

7.0


In [4]:
print(sess.run({'ab':(a,b),'total':total}))

{'total': 7.0, 'ab': (3.0, 4.0)}


In [5]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
z=x+y

In [7]:
print(sess.run(z,feed_dict={x:3,y:4.5}))

7.5


In [8]:
print(sess.run(z,feed_dict={x:[1,2],y:[2,4]}))

[3. 6.]


In [9]:
my_data=[[0,1,],[2,3,],[4,5,],[6,7,],]

slices=tf.data.Dataset.from_tensor_slices(my_data)

next_item=slices.make_one_shot_iterator().get_next()

In [10]:
while True:
    try:
        print(sess.run(next_item))
    except tf.errors.OutOfRangeError:
        break

[0 1]
[2 3]
[4 5]
[6 7]


In [11]:
# 创建层

x=tf.placeholder(tf.float32,shape=[None,3])
linear_model=tf.layers.Dense(units=1)
y=linear_model(x)

In [12]:
init = tf.global_variables_initializer()
sess.run(init)

In [13]:
print(sess.run(y,{x:[[1,2,3],[4,5,6]]}))

[[-0.2408166]
 [ 0.5614872]]


In [14]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))


(None, None)

In [15]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


In [24]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model=tf.layers.Dense(units=1)
y_pred=linear_model(x)

In [25]:
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)
print(sess.run(y_pred))

[[1.2429265]
 [2.485853 ]
 [3.7287793]
 [4.971706 ]]


In [26]:
loss=tf.losses.mean_squared_error(labels=y_true,predictions=y_pred)

print(sess.run(loss))

27.51576


In [27]:
optimizer=tf.train.GradientDescentOptimizer(0.01)
train=optimizer.minimize(loss)

In [29]:
for i in range(100):
    _,loss_val=sess.run((train,loss))
   
    print(loss_val)

19.217756
13.459196
9.46271
6.6888943
4.763467
3.4267228
2.4984584
1.8536333
1.4054857
1.0938122
0.87683964
0.72558224
0.6199274
0.54591954
0.4938748
0.4570741
0.43085492
0.4119823
0.39821118
0.3879841
0.38021994
0.37416887
0.36931053
0.3652836
0.36183748
0.35879844
0.35604554
0.3534952
0.35108918
0.348787
0.34656084
0.34439105
0.3422642
0.34017083
0.3381043
0.33606017
0.33403522
0.33202717
0.33003443
0.32805595
0.326091
0.3241387
0.322199
0.32027143
0.31835574
0.31645176
0.31455928
0.3126783
0.3108087
0.30895028
0.307103
0.30526683
0.3034416
0.3016274
0.299824
0.29803136
0.29624945
0.2944782
0.2927176
0.29096746
0.28922778
0.28749856
0.28577965
0.28407103
0.28237253
0.28068435
0.27900618
0.27733803
0.27567986
0.2740316
0.27239323
0.27076462
0.26914576
0.2675366
0.26593703
0.26434708
0.26276663
0.2611955
0.2596339
0.25808156
0.25653854
0.25500473
0.25348014
0.2519646
0.25045818
0.24896067
0.24747221
0.24599257
0.24452183
0.24305992
0.24160671
0.24016215
0.23872623
0.23729894
0.23588021

In [30]:
mammal=tf.Variable("Elephant",tf.string)
ignition=tf.Variable(451,tf.int16)
floating=tf.Variable(3.1415926,tf.float64)
its_complicated=tf.Variable(12.3-4.85j,tf.complex64)

In [31]:
my_image=tf.zeros([10,299,299,3])

In [34]:
r=tf.rank(my_image)
print(r)

sess.run(r)

Tensor("Rank_2:0", shape=(), dtype=int32)


4

In [35]:
float_tensor=tf.cast(tf.constant([1,2,3]),dtype=tf.float32)

In [53]:
#sess=tf.Session()
with tf.Graph().as_default():
    pass

In [ ]:

with sess.as_default():
    constant = tf.constant([1, 2, 3])
    #tensor1 = constant * constant
    #print tensor1.eval()
    
    p = tf.placeholder(tf.float32)
    t = p + 1.0
    t=tf.Print(t,[t])
    # t.eval()  # This will fail, since the placeholder did not get a value.
    t.eval(feed_dict={p:2.0})  # This will succeed because we're feeding a value
                           # to the placeholder.
    print(t)
    #sess.run(tf.Print(t,[t]))
    t=tf.Print(t,[t])
    result=t+1
    
    sess.run(t)
    sess.run(result)

In [58]:
g1=tf.Graph()
with g1.as_default():
    x=tf.placeholder(tf.float32)
    y=tf.placeholder(tf.float32)
    bias=tf.Variable(1.0)
    y_pre=x**2+bias
    loss=(y-y_pre)**2
    
    sess=tf.Session()
    sess.run(tf.global_variables_initializer())
    print('Loss(x,y)= %.3f' % sess.run(loss,{x:3.0,y:9.0}))

Loss(x,y)= 1.000


In [1]:
import tensorflow as tf

a=tf.constant(1.0,name="a")
b=tf.truncated_normal(shape=[],stddev=1,name="b")

print(a.get_shape())
print(b.get_shape())

/home/dsp2/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


()
()


In [3]:
x=tf.add(a,b)
tf.summary.scalar('x',x)
tf.summary.histogram('x_h',x)

merged=tf.summary.merge_all()
sess=tf.Session()
write=tf.summary.FileWriter('log',sess.graph)

sess.run(tf.global_variables_initializer())
step=0
while True:
    mysum=sess.run(merged)
    write.add_summary(mysum,step)
    step+=1
    if step==100:
        break

write.close()
sess.close()

In [ ]:
import tensorflow as tf

In [8]:
sess=tf.Session()
with sess.as_default():
    constant = tf.constant([1, 2, 3])
    #tensor1 = constant * constant
    #print tensor1.eval()
    
    p = tf.placeholder(tf.float32)
    t = p + 1.0
    t=tf.Print(t,[t]," tf.print(t) :")
    # t.eval()  # This will fail, since the placeholder did not get a value.
    t.eval(feed_dict={p:2.0})  # This will succeed because we're feeding a value
                           # to the placeholder.
    print(t)
    #sess.run(tf.Print(t,[t]))
    #t=tf.Print(t,[t])
    result=t+1
    
    sess.run(t,{p:2.0})
    sess.run(result,{p:2.0})

Tensor("Print_7:0", dtype=float32)


In [10]:
import numpy as np
def my_fun(x):
    return np.sinh(x)

inp=tf.placeholder(tf.float32)

y=tf.py_func(my_fun,[inp],[tf.float32])